config/routes.rb
Rails.application.routes.draw do
  root to: "general#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    get "about-us", to: "general#about-us"
    get "faqs", to: "general#faqs"
    get "search", to: "restaurants#search"
    get "index", to: "general#index"

    resources :restaurants
    get "restaurants/:id", to: "restaurants#show"

    resources :contacts
    get "new-contact", to: "contacts#new"

    resources :users
    get 'login', to: 'sessions#login'
    post 'login', to: 'sessions#create'
    post 'logout' , to: 'sessions#destroy'
    get 'logout', to: 'sessions#logout'
    get "sign-up", to: "users#new"
    post "sign-up", to: "users#create"
    get "users/success", to: "users#success", as: "user_success"
    get "users/failure", to: "users#failure", as: "user_failure"
    get "sessions/success", to: "sessions#success", as: "session_success"
    get "sessions/error", to: "sessions#error", as: "session_error"
    get "my-account", to: "users#myaccount"
    get 'change-info', to: 'users#change_info', as: :change_info
    post '/modify_info', to: 'users#modify_info', as: :modify_info
    get 'change-preferences', to: "users#change-preferences"
    post "modify_preferences", to: "users#modify_preferences", as: :modify_preferences

    #Admin Login
    get '/admin-login', to: 'admins#new'
    post '/admin-login', to: 'admins#create'
    delete '/admin-logout', to: 'admins#destroy'

    #Admin dashboard
    get 'dashboards/index', to: 'dashboards#index', as: "admin_dashboard"
    get 'user_status', to: 'prohibitions#index', as: "user_status"

    #ban user in User Status
    post '/prohibitions/ban/:id', to: 'prohibitions#ban_user', as: "ban_user"
    post '/prohibitions/unban/:id', to: 'prohibitions#unban_user', as: "unban_user"
    get '/prohibitions/search/:search_term', to: 'prohibitions#search', as: "search_user"

    get 'role_verification', to: 'dashboards#role_verification'
    get 'admin-restaurant_info', to: 'info_edit#show'
    get 'admin-restaurant_review', to: 'dashboards#restaurant_review'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/user.rb
class User < ApplicationRecord

    validates :username, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 8 }
    validates :email, presence: true, uniqueness: true

    has_many :reviews

    def banned?
        banned
    end

    def self.search(search)
        if search
            self.where("lower(username) LIKE ?", "%#{search.downcase}%")
        else
            @users = User.all
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_success_path(@user)
    else
      redirect_to user_failure_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def change_info
    @field = params[:field]
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    render 'change-info'
  end

  def modify_info
    @field = params[:field]
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    
    new_value = params[:modify_info][:new_value]

    @user.send("#{@field}=", new_value)

    if @user.save
      redirect_to my_account_path, success: "User information updated successfully."
    else
      render 'change-info', success: "Error modifying"
    end

  end

  def modify_preferences
    @user_id = params[:modify_preferences][:user_id]
    @user = User.find(@user_id)

    preferences_params.each do |preference, value|
      @user.update_attribute(preference, value)
    end

    if @user.save
      redirect_to my_account_path, success: "Dietary preferences updated successfully."
    else
      flash[:notice] = "Error updating dietary preferences."
      render 'change-preferences'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def preferences_params
    params.require(:modify_preferences).permit(
      :gluten_intolerance, :vegan, :vegetarian,
      :nut_allergy, :fish_allergy,
      :egg_allergy, :soy_allergy, :dairy_allergy,
      :kosher, :halal
    )
  end


end

app/views/users/change-info.html.erb
<% stylesheet_link_tag('my-account_style')%>  

<% @current_user = User.find_by_id(session[:user_id]) %>

<h2>Change <%= @field.capitalize %></h2>

<section class="new_accinfo_cont">

    <div class="old-info-section">
        <span class="label">Current <%= @field %>:</span>
        <span class="info"><%= @current_user.send(@field) %></span>
    </div>


    <div class="form-container">
    <%= form_for :modify_info, url: modify_info_path, method: :post do |f| %>
        <%= hidden_field_tag :field, @field %>
        <%= hidden_field_tag :user_id, @current_user.id %>
        <%= f.text_field :new_value, placeholder: @field.capitalize, class:"form-input" %><br>
        <%= f.submit "Submit", class: "form-button" %>
    <% end %>
    </div>

</section>


</body>
</html>

app/views/users/change-preferences.html.erb
<% stylesheet_link_tag('my-account_style') %>

<% @current_user = User.find_by_id(session[:user_id]) %>

<h2>Change Preferences</h2>

<section class="new_accinfo_cont">

  <div class="form-container">
    <%= form_for :modify_preferences, url: modify_preferences_path, method: :post do |f| %>
      <%= f.hidden_field :user_id, value: @current_user.id %>

      <%= f.check_box :gluten_intolerance, checked: @current_user.gluten_intolerance %>
      <%= f.label :gluten_intolerance, 'Gluten Intolerance' %><br>

      <%= f.check_box :vegan, checked: @current_user.vegan %>
      <%= f.label :vegan, 'Vegan' %><br>

      <%= f.check_box :vegetarian, checked: @current_user.vegetarian %>
      <%= f.label :vegetarian, 'Vegetarian' %><br>

      <%= f.check_box :nut_allergy, checked: @current_user.nut_allergy %>
      <%= f.label :nut_allergy, 'Nut Allergy' %><br>

      <%= f.check_box :fish_allergy, checked: @current_user.fish_allergy %>
      <%= f.label :fish_allergy, 'Fish Allergy' %><br>

      <%= f.check_box :egg_allergy, checked: @current_user.egg_allergy %>
      <%= f.label :egg_allergy, 'Egg Allergy' %><br>

      <%= f.check_box :soy_allergy, checked: @current_user.soy_allergy %>
      <%= f.label :soy_allergy, 'Soy Allergy' %><br>

      <%= f.check_box :dairy_allergy, checked: @current_user.dairy_allergy %>
      <%= f.label :dairy_allergy, 'Dairy Allergy' %><br>

      <%= f.check_box :kosher, checked: @current_user.kosher %>
      <%= f.label :kosher, 'Kosher' %><br>

      <%= f.check_box :halal, checked: @current_user.halal %>
      <%= f.label :halal, 'Halal' %><br>

      <%= f.submit "Submit", class: "form-button" %>
    <% end %>
  </div>

</section>

</body>
</html>

app/views/users/failure.html.erb
<!-- Unsuccessful sign up -->

<%= stylesheet_link_tag('login-style')%> 

<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h3>Something went wrong during the sign-up process.</h3>
<p>Please try again. Make sure your username is unique and your password is at least 8 characters.</p>
</body>


</html>

app/views/users/myaccount.html.erb
<% stylesheet_link_tag('my-account_style')%>  

<% @current_user = User.find_by_id(session[:user_id]) %>

<h2>My Account</h2>

<p>Configure account details and choose your preferences.</p>

<section class="accinfo_cont">
    <h2>My Information</h2>

    <div class="info-section">
        <span class="label">Username:</span>
        <span class="info"><%= @current_user.username %></span>
    </div>

    <div class="button-section">
        <a href="<%= change_info_path(field: 'username', user_id: @current_user.id) %>" class="acc-form-button">Change Username</a>
    </div>

    <div class="info-section">
        <span class="label">Email:</span>
        <span class="info"><%= @current_user.email %></span>
    </div>

    <div class="button-section">
        <a href="<%= change_info_path(field: 'email', user_id: @current_user.id) %>" class="acc-form-button">Change Email</a>
    </div>

    <div class="info-section">
        <span class="label">Password:</span>
        <span class="info"><%= '*' * @current_user.password.length %></span>
    </div>
    </div>
</section>


<section class="accinfo_cont">
  <h2>My Preferences</h2>

  <div class="info-section">
    <span class="label">Gluten Intolerance:</span>
    <span class="info"><%= @current_user.gluten_intolerance ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Vegan:</span>
    <span class="info"><%= @current_user.vegan ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Vegetarian:</span>
    <span class="info"><%= @current_user.vegetarian ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Nut Allergy:</span>
    <span class="info"><%= @current_user.nut_allergy ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Fish Allergy:</span>
    <span class="info"><%= @current_user.fish_allergy ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Egg Allergy:</span>
    <span class="info"><%= @current_user.egg_allergy ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Soy Allergy:</span>
    <span class="info"><%= @current_user.soy_allergy ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Dairy Allergy:</span>
    <span class="info"><%= @current_user.dairy_allergy ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Kosher:</span>
    <span class="info"><%= @current_user.kosher ? 'Yes' : 'No' %></span>
  </div>

  <div class="info-section">
    <span class="label">Halal:</span>
    <span class="info"><%= @current_user.halal ? 'Yes' : 'No' %></span>
  </div>

  <div class="button-section">
    <a href="/change-preferences" class="acc-form-button">Change Preferences</a>
  </div>
</section>


<section class="accinfo_cont">
    <h2>Restaurants</h2>
    <div class="button-section">
        <span class="acc-form-button">Add a Restaurant</span>
    </div>
</section>

<div class="form-container">
    <%=form_tag '/logout' do %>
    <%=submit_tag "Log Out", class: "form-button"%>
    <% end %>
</div>



</body>
</html>

app/views/users/new.html.erb
<%= stylesheet_link_tag('login-style')%> 

<!-- Title -->
<h1>Sign Up for mvrf!</h1>

<!-- Blurb -->
<p>Let's get started! Input your information below.</p>

<div class="form-container">
    <h2>Sign Up</h2>
    <%= form_for @user do |f| %>
        <%= f.text_field :username, placeholder:"Username", class:"form-input" %><br>
        <%= f.text_field :email, placeholder:"Email", class:"form-input" %><br>
        <p class="field-requirement">Password (minimum 8 characters):</p>
        <%= f.password_field :password, placeholder:"Password", class:"form-input" %><br>
        <%= f.submit "Create Account", class: "form-button" %>
    <% end %>
</div>



</body>
</html>

app/views/users/success.html.erb
<!-- Successful sign up -->


<% @current_user = User.find_by_id(session[:user_id]) %>


<!DOCTYPE html>
<html>
<body>
<h1>Sign up successful!</h1>
<h2>Welcome, <%= @current_user.username %>!</h2>
</body>
</html>