config/routes.rb
Rails.application.routes.draw do
  root to: "general#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    get "about-us", to: "general#about-us"
    get "faqs", to: "general#faqs"
    get "search", to: "restaurants#search"
    get "index", to: "general#index"

    resources :restaurants
    get "restaurants/:id", to: "restaurants#show"

    resources :contacts
    get "new-contact", to: "contacts#new"

    resources :users
    get 'login', to: 'sessions#login'
    post 'login', to: 'sessions#create'
    post 'logout' , to: 'sessions#destroy'
    get 'logout', to: 'sessions#logout'
    get "sign-up", to: "users#new"
    post "sign-up", to: "users#create"
    get "users/success", to: "users#success", as: "user_success"
    get "users/failure", to: "users#failure", as: "user_failure"
    get "sessions/success", to: "sessions#success", as: "session_success"
    get "sessions/error", to: "sessions#error", as: "session_error"
    get "my-account", to: "users#myaccount"
    get 'change-info', to: 'users#change_info', as: :change_info
    post '/modify_info', to: 'users#modify_info', as: :modify_info
    get 'change-preferences', to: "users#change-preferences"
    post "modify_preferences", to: "users#modify_preferences", as: :modify_preferences

    #Admin Login
    get '/admin-login', to: 'admins#new'
    post '/admin-login', to: 'admins#create'
    delete '/admin-logout', to: 'admins#destroy'

    #Admin dashboard
    get 'dashboards/index', to: 'dashboards#index', as: "admin_dashboard"
    get 'user_status', to: 'prohibitions#index', as: "user_status"

    #ban user in User Status
    post '/prohibitions/ban/:id', to: 'prohibitions#ban_user', as: "ban_user"
    post '/prohibitions/unban/:id', to: 'prohibitions#unban_user', as: "unban_user"
    get '/prohibitions/search/:search_term', to: 'prohibitions#search', as: "search_user"

    get 'role_verification', to: 'dashboards#role_verification'
    get 'admin-restaurant_info', to: 'info_edit#show'
    get 'admin-restaurant_review', to: 'dashboards#restaurant_review'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/controllers/info_edit_controller.rb
class InfoEditController < ApplicationController
  def show
    @restaurants = Restaurant.all
  end

end

app/views/info_edit/show.html.erb
<h1>Restaurant Information</h1>

<%= form_tag admin_restaurant_info_path, method: :get do%>
    <%= text_field_tag :search, params[:search], placeholder: "Search Restaurant's Name or Owner..." %>
    <%= submit_tag "Search"%>
<% end %>

<% if @restaurants.present?%>
    <table>
        <tr>
            <th>Restaurant Name</th>
            <th>Owner</th>
            <th>Dietary Restrictions</th>
            <th>Opening Hours</th>
            <th>Address</th>
            <th>Description</th>
        </tr>
            <% @restaurants.each do |restaurant| %>
                <tr>
                    <td><%= restaurant.name%></td>
                    <td><%= restaurant.owner%></td>
                    <td>
                        <% tags = []%>
                        <% tags << "Gluten Intolerance" if restaurant.gluten_intolerance?%>
                        <% tags << "Vegan" if restaurant.vegan?%>
                        <% tags << "Vegetarian" if restaurant.vegetarian?%>
                        <% tags << "Nut Allergy" if restaurant.nut_allergy?%>
                        <% tags << "Fish Allergy" if restaurant.fish_allergy?%>
                        <% tags << "Egg Allergy" if restaurant.egg_allergy?%>
                        <% tags << "Soy Allergy" if restaurant.soy_allergy?%>
                        <% tags << "Dairy Allergy" if restaurant.dairy_allergy?%>
                        <% tags << "Kosher" if restaurant.kosher?%>
                        <% tags << "Halal" if restaurant.halal?%>
                        <%= tags.join(', ')%> 
                    </td>
                    <td><%= restaurant.hours%></td>
                    <td><%= restaurant.address%></td>
                    <td><%= restaurant.description%></td>
                    <td><%=button_to "Edit"%></td>
                </tr>
            <% end %>
</table>
<%else%>
    <p>No users found in Database.</p>
<% end %>