config/routes.rb
Rails.application.routes.draw do
  root to: "general#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    get "about-us", to: "general#about-us"
    get "faqs", to: "general#faqs"
    get "search", to: "restaurants#search"
    get "index", to: "general#index"

    resources :restaurants
    get "restaurants/:id", to: "restaurants#show"

    resources :contacts
    get "new-contact", to: "contacts#new"

    resources :users
    get 'login', to: 'sessions#login'
    post 'login', to: 'sessions#create'
    post 'logout' , to: 'sessions#destroy'
    get 'logout', to: 'sessions#logout'
    get "sign-up", to: "users#new"
    post "sign-up", to: "users#create"
    get "users/success", to: "users#success", as: "user_success"
    get "users/failure", to: "users#failure", as: "user_failure"
    get "sessions/success", to: "sessions#success", as: "session_success"
    get "sessions/error", to: "sessions#error", as: "session_error"
    get "my-account", to: "users#myaccount"
    get 'change-info', to: 'users#change_info', as: :change_info
    post '/modify_info', to: 'users#modify_info', as: :modify_info
    get 'change-preferences', to: "users#change-preferences"
    post "modify_preferences", to: "users#modify_preferences", as: :modify_preferences

    #Admin Login
    get '/admin-login', to: 'admins#new'
    post '/admin-login', to: 'admins#create'
    delete '/admin-logout', to: 'admins#destroy'

    #Admin dashboard
    get 'dashboards/index', to: 'dashboards#index', as: "admin_dashboard"
    get 'user_status', to: 'prohibitions#index', as: "user_status"

    #ban user in User Status
    post '/prohibitions/ban/:id', to: 'prohibitions#ban_user', as: "ban_user"
    post '/prohibitions/unban/:id', to: 'prohibitions#unban_user', as: "unban_user"
    get '/prohibitions/search/:search_term', to: 'prohibitions#search', as: "search_user"

    get 'role_verification', to: 'dashboards#role_verification'
    get 'admin-restaurant_info', to: 'info_edit#show'
    get 'admin-restaurant_review', to: 'dashboards#restaurant_review'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :description, presence: true, length: {minimum: 10}

    def self.search(search, gluten_req, vegan_req, vegetarian_req,
        nut_allergy_req, fish_allergy_req, egg_allergy_req, soy_allergy_req,
        dairy_allergy_req, kosher_req, halal_req)
        if search
            self.where("lower(name) LIKE ? AND gluten_intolerance >= ? AND vegan >= ? AND vegetarian >= ? AND nut_allergy >= ? AND fish_allergy >= ? AND egg_allergy >= ? AND soy_allergy >= ? AND dairy_allergy >= ? AND kosher >= ? AND halal >= ?",
            "%#{search.downcase}%", gluten_req, vegan_req, vegetarian_req, nut_allergy_req, fish_allergy_req, egg_allergy_req, soy_allergy_req,
            dairy_allergy_req, kosher_req, halal_req).or(self.where("lower(cuisine) LIKE ? AND gluten_intolerance >= ? AND vegan >= ? AND vegetarian >= ? AND nut_allergy >= ? AND fish_allergy >= ? AND egg_allergy >= ? AND soy_allergy >= ? AND dairy_allergy >= ? AND kosher >= ? AND halal >= ?",
            "%#{search.downcase}%", gluten_req, vegan_req, vegetarian_req, nut_allergy_req, fish_allergy_req, egg_allergy_req, soy_allergy_req,
            dairy_allergy_req, kosher_req, halal_req)).or(self.where("lower(address) LIKE ? AND gluten_intolerance >= ? AND vegan >= ? AND vegetarian >= ? AND nut_allergy >= ? AND fish_allergy >= ? AND egg_allergy >= ? AND soy_allergy >= ? AND dairy_allergy >= ? AND kosher >= ? AND halal >= ?",
            "%#{search.downcase}%", gluten_req, vegan_req, vegetarian_req, nut_allergy_req, fish_allergy_req, egg_allergy_req, soy_allergy_req,
            dairy_allergy_req, kosher_req, halal_req)).or(self.where("lower(description) LIKE ? AND gluten_intolerance >= ? AND vegan >= ? AND vegetarian >= ? AND nut_allergy >= ? AND fish_allergy >= ? AND egg_allergy >= ? AND soy_allergy >= ? AND dairy_allergy >= ? AND kosher >= ? AND halal >= ?",
            "%#{search.downcase}%", gluten_req, vegan_req, vegetarian_req, nut_allergy_req, fish_allergy_req, egg_allergy_req, soy_allergy_req,
            dairy_allergy_req, kosher_req, halal_req))
        else
            @restaurants = Restaurant.all
        end
    end


    #Check if Restaurants have which dietary preference
    def gluten_intolerance?
        gluten_intolerance
    end

    def vegan?
        vegan
    end

    def vegetarian?
        vegetarian
    end

    def nut_allergy?
        nut_allergy
    end

    def fish_allergy?
        fish_allergy
    end

    def egg_allergy?
        egg_allergy
    end

    def soy_allergy?
        soy_allergy
    end

    def dairy_allergy?
        dairy_allergy
    end

    def kosher?
        kosher
    end

    def halal?
        halal
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def search
        @restaurants = Restaurant.search(params[:search], params[:gluten_req], params[:vegan_req],
        params[:vegetarian_req], params[:nut_allergy_req], params[:fish_allergy_req],
        params[:egg_allergy_req], params[:soy_allergy_req], params[:dairy_allergy_req],
        params[:kosher_req], params[:halal_req])
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)

        if @restaurant.save
            redirect_to @restaurant
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
    end

    def update
        @restaurant = Restaurant.find(params[:id])

        if @restaurant.update(restaurant_params)
            redirect_to @restaurant
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy

        redirect_to search_path, status: :see_other
    end

    private
        def restaurant_params
            params.require(:restaurant).permit(:name, :owner, :address, :hours, :rating, :ratingsnum, :description, :cuisine,
            :image, :tags, :gluten_intolerance, :vegan, :vegetarian, :nut_allergy,
            :fish_allergy, :egg_allergy, :soy_allergy, :dairy_allergy, :kosher,
            :halal, :search, :gluten_req, :vegan_req, :vegetarian_req,
            :nut_allergy_req, :fish_allergy_req, :egg_allergy_req,
            :soy_allergy_req, :dairy_allergy_req, :kosher_req,
            :halal_req)
        end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :owner %><br>
        <%= form.text_field :owner %>
    </div>

    <div>
        <%= form.label :address %><br>
        <%= form.text_field :address %>
    </div>

    <div>
        <%= form.label :hours %><br>
        <%= form.text_field :hours %>
    </div>

    <div>
        <%= form.label :rating %><br>
        <%= form.number_field :rating, in: 0.0..5.0, step: 0.1 %>
    </div>

    <div>
        <%= form.label :ratingsnum %><br>
        <%= form.number_field :ratingsnum, step: 1 %>
    </div>

    <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label :cuisine %><br>
        <%= form.text_field :cuisine %>
    </div>

    <div>
        <%= form.label :image %><br>
        <%= form.text_field :image %>
    </div>

    <div>
        <%= form.label :tags %><br>
        <%= form.text_field :tags %>
    </div>

    <div>
        <%= form.label :gluten_intolerance%><br>
        <%= form.check_box :gluten_intolerance%>
    </div>

    <div>
        <%= form.label :vegan %><br>
        <%= form.check_box :vegan %>
    </div>

    <div>
        <%= form.label :vegetarian %><br>
        <%= form.check_box :vegetarian %>
    </div>

    <div>
        <%= form.label :nut_allergy %><br>
        <%= form.check_box :nut_allergy %>
    </div>

    <div>
        <%= form.label :fish_allergy %><br>
        <%= form.check_box :fish_allergy%>
    </div>

    <div>
        <%= form.label :egg_allergy %><br>
        <%= form.check_box :egg_allergy %>
    </div>

    <div>
        <%= form.label :soy_allergy %><br>
        <%= form.check_box :soy_allergy %>
    </div>

    <div>
        <%= form.label :dairy_allergy %><br>
        <%= form.check_box :dairy_allergy %>
    </div>

    <div>
        <%= form.label :kosher %><br>
        <%= form.check_box :kosher%>
    </div>

    <div>
        <%= form.label :halal %><br>
        <%= form.check_box :halal %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= form_with model: @restaurant do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :owner %><br>
        <%= form.text_field :owner %>
    </div>

    <div>
        <%= form.label :address %><br>
        <%= form.text_field :address %>
    </div>

    <div>
        <%= form.label :hours %><br>
        <%= form.text_field :hours %>
    </div>

    <div>
        <%= form.label :rating %><br>
        <%= form.number_field :rating, in: 0.0..5.0, step: 0.1 %>
    </div>

    <div>
        <%= form.label :ratingsnum %><br>
        <%= form.number_field :ratingsnum, step: 1 %>
    </div>

    <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label :cuisine %><br>
        <%= form.text_field :cuisine %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/restaurants/search.html.erb
<style>
  .locations {
    margin-top: 20px;
    text-align: center;
  }

  .locations ul {
    list-style-type: none;
    padding: 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }

  .locations .location-item {
    flex: 0 0 12%; /* Adjusted column width */
    margin: 10px;
    text-align: center;
  }

  .locations img {
    width: 240px; /* Set a fixed width */
    height: 150px; /* Set a fixed height */
    object-fit: cover; /* Maintain aspect ratio and cover container */
    border-radius: 8px;
    margin-left: auto;
    margin-right: auto;
  }
</style>

<%= javascript_include_tag "dropdown.js", defer: true %>
<%= javascript_include_tag "switch-views.js", defer: true %>

<% @current_user = User.find_by_id(session[:user_id]) %>


<!--- <input type="text" placeholder="Search..."> -->
<div class = "search-container-container">
  <div class="search-container">
    <%= form_with url: "/search", class: "form", method: :get do |form| %>
      <%= form.text_field :search, placeholder: "Search..." %>

      <% if @current_user %>
        <%= form.hidden_field :gluten_req, value: @current_user.gluten_intolerance %>
        <%= form.hidden_field :vegan_req, value: @current_user.vegan %>
        <%= form.hidden_field :vegetarian_req, value: @current_user.vegetarian %>
        <%= form.hidden_field :nut_allergy_req, value: @current_user.nut_allergy %>
        <%= form.hidden_field :fish_allergy_req, value: @current_user.fish_allergy %>
        <%= form.hidden_field :egg_allergy_req, value: @current_user.egg_allergy %>
        <%= form.hidden_field :soy_allergy_req, value: @current_user.soy_allergy %>
        <%= form.hidden_field :dairy_allergy_req, value: @current_user.dairy_allergy %>
        <%= form.hidden_field :kosher_req, value: @current_user.kosher %>
        <%= form.hidden_field :halal_req, value: @current_user.halal %>
      <% else %>
        <%= form.hidden_field :gluten_req, value: false %>
        <%= form.hidden_field :vegan_req, value: false %>
        <%= form.hidden_field :vegetarian_req, value: false %>
        <%= form.hidden_field :nut_allergy_req, value: false %>
        <%= form.hidden_field :fish_allergy_req, value: false %>
        <%= form.hidden_field :egg_allergy_req, value: false %>
        <%= form.hidden_field :soy_allergy_req, value: false %>
        <%= form.hidden_field :dairy_allergy_req, value: false %>
        <%= form.hidden_field :kosher_req, value: false %>
        <%= form.hidden_field :halal_req, value: false %>
      <% end %>

      <!--- <%= form.submit "Search" %> -->
    <% end %>

      <div class="dropdown">
      <button onclick="OpenFilters()" class="filters-button">Filters</button>
      <div id="filters" class="filters-content">
        <p>Open Now</p>
        <p>Price ($)</p>
        <p>Price ($$)</p>
        <p>Price ($$$)</p>
      </div>
    </div>

    <div class="dropdown">
      <button onclick="OpenSortBy()" class="sorting-button">Sort By</button>
      <div id="sorting" class="sorting-methods">
        <p>A-Z</p>
        <p>Proximity</p>
        <p>Ratings (highest to lowest)</p>
      </div>
    </div>

  </div>
</div>



</div>
<div class="locations">
  <h1>Top Restaurants Near You:</h1>
  <ul>
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Steve's+Pok%C3%A9+Bar/@49.277584,-122.9115997,19.86z/data=!3m1!5s0x548679bee9f6859b:0x9760b0bad355a92e!4m6!3m5!1s0x548679bee9cd6b29:0xcc7439254cced8f8!8m2!3d49.2777957!4d-122.9118286!16s%2Fg%2F11cp7qjrxr?entry=ttu" target="_blank">
        <%= image_tag "search-images/poke.png"%>
        <p>Steve's Poke Bar</p>
      </a>
      <p>Rating: 4.8 </p>
      <p>(638 reviews)</p>
    
    </div>
   <div class="location-item">
      <a href="https://www.google.com/maps/place/Quesada+Burritos+%26+Tacos/@49.277614,-122.9116002,18.82z/data=!3m1!5s0x548679bee9f6859b:0x9760b0bad355a92e!4m6!3m5!1s0x548679bec22c4db3:0xe249b13252ccb70f!8m2!3d49.2778408!4d-122.9114345!16s%2Fg%2F11b5pjqr_m?entry=ttu" target="_blank">
        <%= image_tag "search-images/burritos.png"%>
        <p>Quesada Burritos & Tacos</p>
      </a>
      <p>Rating: 3.9 </p>
      <p>(336 reviews)</p>
    </div>
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Uncle+Fatih's+Pizza+-+SFU/@49.278108,-122.9125523,17z/data=!3m2!4b1!5s0x548679bc11afc0a1:0xc6f61698732e3bf1!4m6!3m5!1s0x548679bea37cca8b:0xd7270caa53b8a287!8m2!3d49.2781045!4d-122.9099774!16s%2Fg%2F11c80851t1?entry=ttu" target="_blank">
        <%= image_tag "search-images/pizza.png"%>
        <p>Uncle Fatih's Pizza</p>
      </a>
      <p>Rating: 4.1 </p>
      <p>(333 reviews)</p>
    </div> 
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Starbucks/@49.278108,-122.9125523,17z/data=!4m6!3m5!1s0x548679bfe16aaaab:0x1e4f5af7b912732f!8m2!3d49.2781416!4d-122.9122678!16s%2Fg%2F11bwlb76wd?entry=ttu" target="_blank">
        <%= image_tag "search-images/starbucks.png"%>
        <p>Starbucks</p>
      </a>
      <p>Rating: 3.5 </p>
      <p>(271 reviews)</p>
    </div>
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Pho+99+SFU/@49.2778792,-122.9149683,17z/data=!3m2!4b1!5s0x548679bee9f6859b:0x9760b0bad355a92e!4m6!3m5!1s0x5486798d67f2f439:0x335471a8315fb75e!8m2!3d49.2778757!4d-122.9123934!16s%2Fg%2F11j15h_8h6?entry=ttu" target="_blank">
        <%= image_tag "search-images/pho99.png"%>
        <p>Pho 99 SFU</p>
      </a>
      <p>Rating: 4.3 </p>
      <p>(270 reviews)</p>
    </div>
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Renaissance+Coffee/@49.2786987,-122.9178839,18.82z/data=!4m6!3m5!1s0x548679bff0174595:0xa7a778ea0efdcdc2!8m2!3d49.2793994!4d-122.9156363!16s%2Fg%2F1thd6cbr?entry=ttu" target="_blank">
        <%= image_tag "search-images/coffee.png"%>
        <p>Renaissance Coffee</p>
      </a>
      <p>Rating: 4.1 </p>
      <p>(177 reviews)</p>
    </div>
    <div class="location-item">
      <a href="https://www.google.com/maps/place/Japarrito/@49.2778353,-122.9117616,20.39z/data=!3m1!5s0x548679bee9f6859b:0x9760b0bad355a92e!4m6!3m5!1s0x548679beeb22f875:0xc0a7d84afd27370b!8m2!3d49.2780824!4d-122.9119066!16s%2Fg%2F1vg_ck9v?entry=ttu" target="_blank">
        <%= image_tag "search-images/japarrito.png"%>
        <p>Japarrito</p>
      </a>
      <p>Rating: 3.7 </p>
      <p>(125 reviews)</p>
    </div>
    
    <!-- Repeat for other locations -->
    <!-- ... -->
  </ul>
</div>

<div class="main-content">
  <div class="sidebar">
    <h2 class="results">Results</h2>

    <% @restaurants.each do |restaurant| %>
      <button onclick="SwitchRestaurantView(<%= restaurant.id %>)" class="sidebar-element">
        <p class="restaurant-name"><%= restaurant.name %></p>
        <div class="address-ratings">
          <p class="address"><%= restaurant.address %></p>
          <p class="ratings"> <%= restaurant.rating%> </p>
        </div>
        <div class="tags-cuisine">
          <p class="tags"><%= restaurant.tags %></p>
          <p class="cuisine">Cuisine: <%= restaurant.cuisine%></p>
        </div>
      </button>
    <% end %>
  </div>
 
  <div class="large-view">
    <% @restaurants.each do |restaurant| %>
      <div id="<%= restaurant.id %>" class="restaurant-view">
        <h1 class="view-name"><%= restaurant.name %></h1>
        <div class="image-gallery">
          <img src="<%= restaurant.image %>">
        </div>
        <div class="info-bar">
          <p class="view-address"><%= restaurant.address %></p>
          <p class="view-rating">Rating: <%= restaurant.rating %></p>
          <P class="view-owner">Owner: <%= restaurant.owner %></p>
          <p class="view-cuisine">Cuisine: <%= restaurant.cuisine %></p><br>
          <p class="view-hours">Hours: <%= restaurant.hours %></p>
        </div>
        <div class="description-div">
          <P class="description"><%= restaurant.description %></p>
        </div>
      </div>
    <% end %>

    <div id="map" class="map-view show">
      <%= js_map [{ latitude: 49.2781, longitude: -122.9199, label: "You Are Here" }] %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.description %></p>

<ul>
    <li><%= link_to "Edit", edit_restaurant_path(@restaurant) %></li>
    <li><%= link_to "Destroy", restaurant_path(@restaurant), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %></li>
</ul>