config/routes.rb
Rails.application.routes.draw do
  root to: "general#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    get "about-us", to: "general#about-us"
    get "faqs", to: "general#faqs"
    get "search", to: "restaurants#search"
    get "index", to: "general#index"

    resources :restaurants
    get "restaurants/:id", to: "restaurants#show"

    resources :contacts
    get "new-contact", to: "contacts#new"

    resources :users
    get 'login', to: 'sessions#login'
    post 'login', to: 'sessions#create'
    post 'logout' , to: 'sessions#destroy'
    get 'logout', to: 'sessions#logout'
    get "sign-up", to: "users#new"
    post "sign-up", to: "users#create"
    get "users/success", to: "users#success", as: "user_success"
    get "users/failure", to: "users#failure", as: "user_failure"
    get "sessions/success", to: "sessions#success", as: "session_success"
    get "sessions/error", to: "sessions#error", as: "session_error"
    get "my-account", to: "users#myaccount"
    get 'change-info', to: 'users#change_info', as: :change_info
    post '/modify_info', to: 'users#modify_info', as: :modify_info
    get 'change-preferences', to: "users#change-preferences"
    post "modify_preferences", to: "users#modify_preferences", as: :modify_preferences

    #Admin Login
    get '/admin-login', to: 'admins#new'
    post '/admin-login', to: 'admins#create'
    delete '/admin-logout', to: 'admins#destroy'

    #Admin dashboard
    get 'dashboards/index', to: 'dashboards#index', as: "admin_dashboard"
    get 'user_status', to: 'prohibitions#index', as: "user_status"

    #ban user in User Status
    post '/prohibitions/ban/:id', to: 'prohibitions#ban_user', as: "ban_user"
    post '/prohibitions/unban/:id', to: 'prohibitions#unban_user', as: "unban_user"
    get '/prohibitions/search/:search_term', to: 'prohibitions#search', as: "search_user"

    get 'role_verification', to: 'dashboards#role_verification'
    get 'admin-restaurant_info', to: 'info_edit#show'
    get 'admin-restaurant_review', to: 'dashboards#restaurant_review'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<h1>Site Administrator Dashboard</h1>

<h2 id="admin-h2">Hello, <%= current_admin.username %></h2>
<h3 id="admin-h3">Choose your desire action below:</h3>

<div class = "admin-actions">
    <ul>
        <li><a href="/user_status" id="admin-user-status">User Status</a></li>
        <li><a href="/role_verification" id="admin-role-verification">Role Verification</a></li>
        <li><a href="/admin-restaurant_review" id="admin-restaurant-review">Restaurant Review</a></li>
        <li><a href="/admin-restaurant_info" id="admin-restaurant-info">Restaurant Information</a></li>
    </ul>
</div>

<%=button_to "Log Out",admin_logout_path, method: :delete, class: "admin-logout"%>

app/views/dashboards/restaurant_review.html.erb
<h1>Restaurant Review</h1>

app/views/dashboards/role_verification.html.erb
<h1>Role Verification</h1>

app/views/dashboards/user_status.html.erb
<h1>User Status</h1>

<% if @users.present?%>
    <table>
        <tr>
            <th>Username</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.username%></td>
                    <td><%= user.banned? ? 'Banned' : 'Active' %></td>
                    <% if user.banned? %>
                        <td><%=button_to "Unban",unban_user_path(user), method: :post%></td>
                    <% else %>
                        <td><%=button_to "Ban",ban_user_path(user), method: :post%></td>
                    <% end %>
                </tr>
            <% end %>
</table>
<%else%>
    <p>No users found in Database.</p>
<% end %>